site_name: '{{cookiecutter.project_name}}'
repo_url: '{{cookiecutter.gh_url_project}}'
repo_name: '{{cookiecutter.gh_name_project}}'

theme:
  name: material
  language: pt-BR
  features:
  - navigation.footer
  - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [app]

watch:
  - app
