name: ci
on: push

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          python-version: '3.10'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python Dependencies
        run: pip install poetry cookiecutter

      - name: Check
        run: |
          ls -l
          cookiecutter --no-input .
          cd name-of-the-project
          poetry install --without doc

      - name: Run tests
        run: poetry run task test --cov-report=xml
