name: ci
on: push

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install poetry cookiecutter

      - name: CookieCutter Teste
        run: cookiecutter --no-input .

      - name: Install project
        run: |
          ls -l
          cd name-of-the-project
          poetry install --without doc

      - name: Run tests
        run: poetry run task test --cov-report=xml
